title: "Zhixian Yang's Academic Homepage"
description: "Zhixian Yang's personal website, showcasing his research focus."
author: "Zhixian Yang"
theme: minima

google_site_verification: 8w6lfu4dDeDjStoCmhWVGrgMo685KX02pq8Y1LscXeY

navigation:
  - title: Home
    url: /
  - title: Research
    url: /research
  - title: Education
    url: /education
  - title: RBM recruit
    url: /rbm_recruit

assets:
  - /assets/css/style.css

webmaster_verifications:

footer: "Â© 2025 Zhixian Yang | All rights reserved."